host: 0.0.0.0:8080

db-url: golang_api:golang_api_123@tcp(localhost:3306)/golang_api?charset=utf8mb4&parseTime=True&loc=Local

log:
  path: ./logs
  level: debug
  format: |
    %millisecond_format% (%file% %line%) [%level_string%] %body%